### ISSUE TITLE
WebSocket is not open, start to open it

### ISSUE THREAD

**Issue by fpfgithub** [isxuelinme/poe_unoffical_api#1]
[Info] 2023/03/13 11:25:52 [WebSocket is not open, start to open it] 
github.com/isxuelinme/poe_unoffical_api/core.(*PoeGPT).PoeWsClient(0xc000100090)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/poe.go:363 +0xfd

[Error] 2023/03/13 11:25:54 dial:
(*errors.errorString)
  (errors.errorString)
    s(string) ""
(int) 403

---stacks---
github.com/isxuelinme/poe_unoffical_api/core.(*PoeGPT).PoeWsClient(0xc0000d2090)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/poe.go:374 +0x43d
created by github.com/isxuelinme/poe_unoffical_api/core.NewPoeGPT
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/poe.go:57 +0x2aa

[Info] 2023/03/13 11:44:42 [db_insert repeat message id] 
github.com/isxuelinme/poe_unoffical_api/core.(*UserChat).NewPersistenceConsumer.func1({0xc0001bc0c0?, 0x76a090?}, {0xc0001c0101?, 0xc00004bf18?}, 0xc00004bfd0?)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/gpt.go:272 +0x1e5

[Error] 2023/03/13 11:44:43 [statusCode is not 200]
---stacks---
github.com/isxuelinme/poe_unoffical_api/core.(*PoeGPT).Talk(0xc0000d2090, {0xc00007ac60?, 0x0?}, 0xc00007ac60)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/poe.go:153 +0x38a
github.com/isxuelinme/poe_unoffical_api/core.(*UserChat).Ask(0xc00007ac90, 0xc00007ac30?)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/gpt.go:106 +0xc7
github.com/isxuelinme/poe_unoffical_api/core.(*MultiUserGpt).Talk(0xc000016160, 0xc00007ac60)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/gpt.go:95 +0x1b2
main.main()
        /www/wwwroot/poe_unoffical_api-main/poe_example/main.go:18 +0x6c

[Info] 2023/03/13 11:44:43 [db_insert repeat message id] 
github.com/isxuelinme/poe_unoffical_api/core.(*UserChat).NewPersistenceConsumer.func1({0x0?, 0x0?}, {0x0?, 0x0?}, 0x0?)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/gpt.go:272 +0x1e5

{"type":"dialServiceWithCallbackResponse","callback_func_name":"","data":{"id":"","account":"","parent_message_id":"","conversation_id":"","is_end":true,"text":"","suggestions":null,"error":"statusCode is not 200"}}
[Error] 2023/03/13 11:44:43 发生错误
(string) "statusCode is not 200"

---stacks---
github.com/isxuelinme/poe_unoffical_api/core.(*UserChat).NewMessageNotify.func2({0x6f1cdf, 0x3}, {0x6f54f2, 0x10}, 0xc000064bc0)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/gpt.go:183 +0x8b6
github.com/isxuelinme/poe_unoffical_api/internal/messageQueue.(*MemoryMessageQueue).callConsumer(0xc00008c180, {0x6f1cdf, 0x3}, {0x6f54f2, 0x10}, 0xc0003ecea0, 0xc000064bc0, 0x0?)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/internal/messageQueue/mem_mq.go:80 +0xa8
created by github.com/isxuelinme/poe_unoffical_api/internal/messageQueue.(*MemoryMessageQueue).workByCall
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/internal/messageQueue/mem_mq.go:140 +0x1f8

[Info] 2023/03/13 11:44:43 Cancel
(*errors.errorString)
  (errors.errorString)
    s(string) ""
 
github.com/isxuelinme/poe_unoffical_api/core.(*UserChat).NewMessageNotify.func1(0xc00020e960)
        /root/go/pkg/mod/github.com/isxuelinme/poe_unoffical_api@v1.0.1/core/gpt.go:118 +0x416

作者你好，尝试运行 poe_example/main.go  输出WebSocket is not open 运行需要单独的脚本启动ws吗

**Comment by isxuelinme** [comment]
I found one mistake, wil fix later

**Comment by isxuelinme** [comment]
am fixed all bug or issue,
change version about the repo of go.mod and review readme.md again 
if you have any question , let me know
