### ISSUE TITLE
connect: connection refused -- does not return answer

### ISSUE THREAD

**Issue by zukixa** [isxuelinme/poe_unoffical_api#6]
M1 Mac, been playing with the repository -- but I seem to be having some issue.

Error:

1) go run main.go

2) after input of question:
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/56563509/229264395-9d86f9c3-dab3-41e0-a63f-993de9f78849.png">

3) after error:
![error4](https://user-images.githubusercontent.com/56563509/229264318-a66ff9ec-8b44-44c2-8005-b30eda39810e.jpg)

.env:
![error3](https://user-images.githubusercontent.com/56563509/229264326-b8bba64e-7d7e-49d1-bf6f-bf342012bf34.jpg)

**Comment by isxuelinme** [comment]
you proxy has some wrong, plz check your proxy health

**Comment by isxuelinme** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/13929427/229265216-5da99664-4e54-4a46-a85b-5d254cbb58d1.png">
it represents your proxy connect failed

**Comment by zukixa** [comment]
I'm not *intending* to use a proxy, it can be without one, as the proxy is just the "proxy" from the example

If I don't want a proxy, do I just remove? Because then I get no answer

**Comment by isxuelinme** [comment]
if you dont use proxy, you must outside of china or another no-blocked poe country,
such as if you are in USA，you dont need to set HTTP_PROXY

**Comment by zukixa** [comment]
ah, thank you!!

I still have some problem, I think with cookies 
I send a request with main.go, but I do not get any response

cookies also reset very fast, this is an old cookie: rizsaJnDaJTSKJ4qjUCP3w%3D%3D
are they this short?

**Comment by isxuelinme** [comment]
if you don't got response you have to show your log

**Comment by zukixa** [comment]
where is the log / how do I activate it

**Comment by isxuelinme** [comment]
maybe you need to relog your account on poe, and reget your poe cookie and another configuration
